### PR TITLE
[feat] add FigmaSpec design block

### PR DESCRIPTION
**Pull request by hazem3500**

### CODE REVIEW

**Comment by hazem3500** [comment]
Related: #70

**Review by pocka — COMMENTED** [review]
Thanks! Could you replace `FigmaSpec` with `Figspec` and somehow mark the block as experimental?

**Comment by hazem3500** [comment]
will do 👍

**Comment by hazem3500** [comment]
@pocka how would you like to mark it as experimental? 
we could add a `console.warn` or rename the Block component to `_Figspec` or `ExperimentalFigspec`, which approach should we take?

**Comment by pocka** [comment]
@hazem3500 
I prefer `console.warn` or `ExperimentalFigspec`. But no strong opinion, any approach that users easily notice the feature as experimental would be okay 👍

**Comment by hazem3500** [comment]
@pocka done 👍

**Comment by pocka** [comment]
Release: v6.0.0-alpha.2

**Pull request merged**
