### PR TITLE
Add panel paramKey to be able to disable

### PR DESCRIPTION
**Pull request by matheo**
Storybook allows to disable the panel for some stories if we configure them like
```
design: { disabled: true },
```
I want this to be the default for my installation, and only show the panel for stories with
```
design: config({...}),
```
Thanks in advance! and thanks for this great addon!

### CODE REVIEW

**Comment by pocka** [comment]
`disable: true` is not working now? If so, would you include an example story to `examples/`?  `TESTS/Issues/#54` is a good place to write the story.

**Comment by matheo** [comment]
@pocka without the `paramKey` it doesn't work.
tomorrow I will include the test story ;)

**Comment by matheo** [comment]
@pocka I've overhauled the examples with the story-sourcecode addon, so it's easier to check the required stuff in the story without dig in Github ;)

Also, I took the liberty to update to the latest stable Storybook so we can use `showPanel` to open the addons by default.

I hope you like it!

**Comment by pocka** [comment]
@matheo Can you revert 3de399c381b241449d14e534781b5948dde4dbf6 and d5faf9b82ab303742b02e17c9bdd9c2055eacae1 so I can merge this PR into v5.3.0 branch without conflicts? Once it seems fine, I'll change the base branch to `v5.3.0` and merge into it, then add StorySource addon to examples. (Please include only relevant changes.)

**Comment by matheo** [comment]
@pocka Silly me! I should have realized to branch your v5.3.0 and see your improved docs! awesome stuff!

I had the time to rebase on the top of your v5.3.0 branch and it seems that my changes are not a lot there, please give a try to the story-source as it will be self explanatory for the people checking the Stories. PR moved to #57

**Pull request closed without merging**
